language: r
cache: packages
sudo: required
warnings_are_errors: false

r_check_args: "--no-vignettes"

r_packages:
  - covr
  - callr

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-base

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master

